config/routes.rb
Rails.application.routes.draw do
  get 'home/profile' => 'home#profile'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'
  resources :users
  resources :notesheets
  resources :courses
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :courses
    has_many :notesheets
    
    
    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true

    
    def self.sign_in_from_omniauth(auth)
        find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
    end
    
    def self.create_user_from_omniauth(auth)
        create(
            provider: auth['provider'],
            uid: auth['uid'],
            name: auth['info']['name']
        )
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :usertype)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<script>
  function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().
    console.log('statusChangeCallback');
    console.log(response);                   // The current login status of the person.
    if (response.status === 'connected') {   // Logged into your webpage and Facebook.
      testAPI();  
    } else {                                 // Not logged into your webpage or we are unable to tell.
    }
  }


  function checkLoginState() {               // Called when a person is finished with the Login Button.
    FB.getLoginStatus(function(response) {   // See the onlogin handler
      statusChangeCallback(response);
    });
  }
  
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '680538159135435',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v5.0'
    });
    
    FB.getLoginStatus(function(response) {   // Called after the JS SDK has been initialized.
      statusChangeCallback(response);        // Returns the login status.
    });
  };
    

  (function(d, s, id) {                      // Load the SDK asynchronously
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

 
  function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', {fields: 'name, id, picture, email'}, function(response) {
      console.log('Successful login for: ' + response.name);
      console.log('ID: ' + response.id)
      console.log('Email: ' + response.email)
      document.getElementById('nameID').setAttribute('value', response.name)
      document.getElementById('emailID').setAttribute('value', response.email)
      console.log('Picture: ' + response.picture)
      
      var name = response.name
      var email = response.email
      console.log(name)

    });
  }
  
  function startLogout(){
    FB.logout(function(response){
      statusChangeCallback(response)
    });
  }
  
  function startLogin() {
    FB.login(function(response){
      statusChangeCallback(response)
    }, {scope: 'email'});
  }
  
  function signUp() {    
  }
</script>
<%= bootstrap_form_for(@user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-50 p-3" style="background-color:#F0F0F0">
    <form>
      <div class="field">
        <%= form.text_field :name, :readonly => true, :id => "nameID"%>
      </div>
      
      <div class="field">
        <%= form.text_field :email, :readonly => true, :value => 's' , :id => "emailID"%>
      </div>
    
      <div class="field">
        <%= form.text_field :password, :class => "form-control", :type => "password" %>
      </div>
      
      <div class="field">
        <%= form.select :usertype, ['Student','Professor','Admin'] %>
      </div>
      
      <div class="actions">
        <%= form.submit %>
      </div>
    </form>
  
  
<% end %>

app/views/users/_signup.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h1>its me so u know</h1>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>
  
  <div class="field">
    <%= form.label :usertype %>
    <%= form.select :usertype, ['Student','Professor','Admin'] %>
   
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<title>NoteShare</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<body style="background-color:#C1DFF0">

<div style="margin-left:25px">
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>
</body>

app/views/users/index.html.erb
<title>NoteShare</title>

<body>
<h1>Users</h1>
<div>
  <%= link_to 'Add New User', new_user_path, :class => "btn btn-success",  :style => "color:black" %>
</div>
<p id="notice"><%= notice %></p>
<table id="dt" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Usertype</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.usertype %></td>
        <td style="padding:5px"><%= link_to 'Show', user %></td>
        <td style="padding:5px">
          <%= link_to 'Edit User Info', edit_user_path(user), :class => "btn btn-warning" %>
        </td>
        <td style="padding:5px">
          <%= button_to 'Destroy', user, method: :delete, :class => "btn btn-danger", data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

</body>

app/views/users/new.html.erb
<body onload = "startLogin()">
<h1>New User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Back', '/' %>
</body>

app/views/users/show.html.erb
<title>NoteShare</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<body>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Usertype:</strong>
  <%= @user.usertype %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', courses_path %>
<br>
</body>