config/routes.rb
Rails.application.routes.draw do
  get 'home/profile' => 'home#profile'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy', as: 'sign_out'
  resources :users
  resources :notesheets
  resources :courses
  root 'home#index'
end

app/models/notesheet.rb
class Notesheet < ApplicationRecord
    belongs_to :course
    belongs_to :user
    
    mount_uploader :notepic, NotepicUploader
    validates :content, presence: true, unless: ->(notesheet){notesheet.notepic.present?}
    validates :notepic, presence: true, unless: ->(notesheet){notesheet.content.present?}
    
    validates :course_id, presence: true
    validates :user_id, presence: true
    validates :date_created, presence: true
    validates :title, presence: true
end

app/controllers/notesheets_controller.rb
class NotesheetsController < ApplicationController
  before_action :set_notesheet, only: [:show, :edit, :update, :destroy]

  # GET /notesheets
  # GET /notesheets.json
  def index
    @notesheets = Notesheet.all
  end

  # GET /notesheets/1
  # GET /notesheets/1.json
  def show
  end

  # GET /notesheets/new
  def new
    @notesheet = Notesheet.new
  end

  # GET /notesheets/1/edit
  def edit
  end

  # POST /notesheets
  # POST /notesheets.json
  def create
    @notesheet = Notesheet.new(notesheet_params)
    
    respond_to do |format|
      if @notesheet.save
        if !@notesheet.notepic.url
            path = "#{@notesheet.title}-#{@notesheet.id}.txt"
            File.open(path, "w+") do |f|
              f.write(@notesheet.content)
              @notesheet.notepic = f
            end
            @notesheet.save!
        end
        
        
        format.html { redirect_to @notesheet, notice: 'Notesheet was successfully created.' }
        format.json { render :show, status: :created, location: @notesheet }
      else
        format.html { render :new }
        format.json { render json: @notesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notesheets/1
  # PATCH/PUT /notesheets/1.json
  def update
    respond_to do |format|
      if @notesheet.update(notesheet_params)
        format.html { redirect_to @notesheet, notice: 'Notesheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @notesheet }
      else
        format.html { render :edit }
        format.json { render json: @notesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notesheets/1
  # DELETE /notesheets/1.json
  def destroy
    @notesheet.destroy
    respond_to do |format|
      format.html { redirect_to notesheets_url, notice: 'Notesheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notesheet
      @notesheet = Notesheet.find(params[:id])

    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def notesheet_params
      params.require(:notesheet).permit(:content, :title, :course_id, :user_id, :date_created, :notepic, :notepic_cache)
    end
end

app/helpers/notesheets_helper.rb
module NotesheetsHelper
end

app/views/notesheets/_form.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<script>
  function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().
    console.log('statusChangeCallback');
    console.log(response);                   // The current login status of the person.
    if (response.status === 'connected') {   // Logged into your webpage and Facebook.
      testAPI();  
    } else {                                 // Not logged into your webpage or we are unable to tell.
    }
  }


  function checkLoginState() {               // Called when a person is finished with the Login Button.
    FB.getLoginStatus(function(response) {   // See the onlogin handler
      statusChangeCallback(response);
    });
  }
  
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '680538159135435',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v5.0'
    });
    
    FB.getLoginStatus(function(response) {   // Called after the JS SDK has been initialized.
      statusChangeCallback(response);        // Returns the login status.
    });
  };
    

  (function(d, s, id) {                      // Load the SDK asynchronously
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

 
  function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', {fields: 'name, id, picture, email'}, function(response) {
      console.log('Successful login for: ' + response.name);
      console.log('ID: ' + response.id)
      console.log('Email: ' + response.email)
      document.getElementById('nameID').setAttribute('value', response.name)
      document.getElementById('emailID').setAttribute('value', response.email)
      console.log('Picture: ' + response.picture)
      
      var name = response.name
      var email = response.email
      console.log(name)

    });
  }
  
  function startLogout(){
    FB.logout(function(response){
      statusChangeCallback(response)
    });
  }
  
  function startLogin() {
    FB.login(function(response){
      statusChangeCallback(response)
    }, {scope: 'email'});
  }
  
  function signUp() {    
  }
</script>
<% auth = FbGraph2::Auth.new('680538159135435', '728f73e88988a9e5c94e879431252701') %>
<% signed_request = auth.from_cookie cookies %>
<% graph = Koala::Facebook::API.new(signed_request.access_token) %>
<% user = graph.get_object('me', fields:'email') %>
<% $currentUserEmail = user['email'] %>
<% $currentUser = User.find_by(email: $currentUserEmail) %>

<%= bootstrap_form_for(@notesheet) do |form| %>
  <% if notesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notesheet.errors.count, "error") %> prohibited this notesheet from being saved:</h2>

      <ul>
        <% notesheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-50 p-3" style="background-color:#F0F0F0">
    <form>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.collection_select :course_id, $currentUser.courses.order(:name),:id,:name, include_blank: true %>
        </div>
    
        <div class="form-group col-md-6">
          <%= form.text_field :title, class: "form-control hidden"%>
        </div>
      </div>
      
      <ul class="nav nav-tabs" id="nav-tab" role="tablist">
        <li class="active"><a data-toggle="tab" href="#textentry" style="color: #333;">Text Entry</a></li>
        <pre>  |  </pre>
        <li style="padding-right: 10px"><a data-toggle="tab" href="#uploading" style="color: #333;">Upload a File
        </a></li>
      </ul>
      
      <div class="tab-content">
        <div id="textentry" class="tab-pane fade in active">
          <%= form.text_area :content, hide_label: true%>
        </div>
        
        <div id="uploading" class="tab-pane fade">
          <div class="field">
            <a href="#" data-toggle="tooltip" title="For best results while viewing, upload a JPG or JPEG."> <i class="fas fa-info-circle", style="color: #333;"></i></a>
            <%= form.file_field :notepic, hide_label: true%>
            <%= form.hidden_field :notepic_cache %>
            
            <script type="application/javascript">
              $('.custom-file-input').change(function(e){
                  var fileName = e.target.files[0].name;
                  $(`.custom-file-label[for=${e.currentTarget['id']}]`).html(fileName);
              }); 
            </script>
          </div>
          
        </div>
      </div>
    
      <div class="field">
          <%= form.hidden_field :user_id, value: $currentUser.id %>
      </div>
      
      
    
      <div class="field">
        <%= form.date_field :date_created, label: "Class date", max: Date.today, value: Date.today %>
      </div>
    
      <div class="actions">
        <%= form.submit %>
      </div>
    </form>
  </div>
  

<% end %>

app/views/notesheets/edit.html.erb
<title>NoteShare</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<body style="background-color:#C1DFF0">

<div style="margin-left:25px">
<h1>Editing Notesheet</h1>

<%= render 'form', notesheet: @notesheet %>

<%= link_to 'Show', @notesheet %> |
<%= link_to 'Back', notesheets_path %>
</div>
</body>

app/views/notesheets/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<style style="text/css">
	/* Define the default color for all the table rows */
	/* Define the hover highlight color for the table row */
  .hoverTable tbody tr:hover {
    background-color: #F2F4F4;
  }
</style>

<title>NoteShare</title>

<body>
<h1>My Notesheets</h1>
<div>
  <%= link_to '+ Create New Notesheet', new_notesheet_path, :class => "btn btn-outline-secondary",  :style => "color:black" %>
</div>
<p id="notice"><%= notice %></p>
<table id="dt" class="table table-bordered table-sm hoverTable" cellspacing="0" width="100%">
  <thead class = "thead-light">
    <tr>
      <th>Title</th>
      <th>Course</th>
      <th>Date Created</th>
      <th>Download</th>
      <th>Edit</th>
      <th>Delete</th>
      <!--<th colspan="2">Actions</th>-->
    </tr>
  </thead>
  
  

<% $currentUser = User.find_by(email: $currentUserEmail) %>


  <tbody>
    <% $currentUser.notesheets.each do |notesheet| %>
      <tr>
        <td><%= link_to notesheet.title, notesheet, :style=>'color:#000000;' %></td>
        <td><%= idToModel(notesheet.course_id, Course).name %></td>
        <td><%= notesheet.date_created %></td>
        <td>
          <a href=<%=notesheet.notepic.url%> download><i class="fas fa-file-download", style='color:#000000'></i><a>
        </td>
        <td>
          <a href=<%=edit_notesheet_path(notesheet)%>>
          <i class="fas fa-edit", style='color:#000000'></i>
          <a>
        </td>
        <td>
          <%= button_to notesheet, method: :delete, :class => "btn btn-outline-dark", :style=>'color:#000000', data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash-alt"></i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div>
  <%= link_to 'Back to Courses', courses_path, :class => "btn btn-outline-secondary",  :style => "color:black" %>
</div>

</body>

app/views/notesheets/new.html.erb
<title>NoteShare</title>
<!--<body onload="startLogin();">-->
<h1>New Notesheet</h1>

<%= render 'form', notesheet: @notesheet %>

<%= link_to(notesheets_path(@notesheet), :style=>'color:#000000') do%>
  <i class="fas fa-chevron-circle-left", style='color:#000000'></i>Back
<%end%>
</body>

app/views/notesheets/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<title>NoteShare</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<style>
  .noteimages{
    width: 600px;
  }
</style>
<body>


<p id="notice"><%= notice %></p>
<p>
  <strong>Course:</strong>
  <%= idToModel(@notesheet.course_id, Course).name %>
</p>

<p>
  <strong>Author:</strong>
  <%= idToModel(@notesheet.user_id, User).name %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @notesheet.date_created %>
</p>

<% unless @notesheet.content.nil? %>
  <p>
    <%= @notesheet.content %>
  </p>
<%end%>

<div style="background-color:#F0F0F0">
  <div class="noteimages">
    <%= image_tag(@notesheet.notepic.url, alt: 'Image of notes') if !@notesheet.content? %>
  </div>
</div>

<br>
<%= link_to 'Back to Courses', courses_path, :class => "btn btn-default",  :style => "color:black" %>
<br>
<%= link_to 'Back to My Notesheets', notesheets_path, :class => "btn btn-default",  :style => "color:black" %>


</body>